### ISSUE TITLE
NOAA example

### ISSUE THREAD

**Issue by AndrewIrwin** [gaelforget/OceanRobots.jl#11]
In the NWP_NOAA example, the function call to draw the line plot references "var" but I think this should be var_b:
lines(dt,x[!,Symbol(var)])

**Comment by gaelforget** [comment]
It's a bit tricky but I think it should be `var`  since `var_b` is rather the output of the `@bind` macro (a `PlutoRunner.Bond` according to `typeof(var_b)`). The UI element gets inserted in the markdown by `$(var_b)` (second line below) but it ultimately sets `var` (see to the right of `@bind` in the first line below). 

```
var_b = @bind var Select(names(x), default="PRES")
md"""Select variable : $(var_b)"""
```

**Comment by gaelforget** [comment]
I'll close this under the assumption that you agree
